### PR TITLE
Update table.html

### PR DESCRIPTION
**Pull request by mandaujjwalapriyadarshini**

### CODE REVIEW

**Comment by mandaujjwalapriyadarshini** [comment]
yrfyt

**Comment by mandaujjwalapriyadarshini** [comment]
jkjkkll

**Comment by amruthavarshinisoma** [comment]
gccccc

**Review by amruthavarshinisoma — COMMENTED** [review]
reviewed

**Comment by mandaujjwalapriyadarshini** [comment]
helllo

**Pull request merged**
